### ISSUE TITLE
Fast polygonization via https://github.com/nenadmarkus/gridhopping ?

### ISSUE THREAD

**Issue by lf94** [mkeeter/fidget#147]
Was just browsing Github's SDF results and this looked interesting. Would this be applicable to fidget? Seems like an interesting algorithm based off the usual sphere tracing / marching...

**Comment by mkeeter** [comment]
I took a look, but don't think it's applicable:

- It's using raycasting to find active cells, which means that the underlying model must have [Lipshitz continuity](https://en.wikipedia.org/wiki/Lipschitz_continuity) with a known constant.  I avoid that restriction in libfive + fidget by using interval arithmetic, which is more flexible (at the cost of being more conservative)
- Actual meshing is done with marching cubes, which isn't the best algorithm (it doesn't preserve sharp features, among other complaints)
