### ISSUE TITLE
Passing variables to meshing

### ISSUE THREAD

**Issue by waywardmonkeys** [mkeeter/fidget#183]
When using code similar to https://docs.rs/fidget/latest/fidget/mesh/index.html, if your shape needs variables, how can you pass them through?

There doesn't seem to be a way to get them to an eval call.

 I guess the same is true for the render APIs?

**Comment by waywardmonkeys** [comment]
In this case, we're constructing the shape via:

```
        let radius_var = Var::new();
        let tree = (x.square() + y.square() + z.square()).sqrt() - radius_var;
        let shape = VmShape::from(tree);
 ```

**Comment by mkeeter** [comment]
I'm working on fixing both this and #182 with a new `ShapeVars` object, stay tuned...

**Comment by waywardmonkeys** [comment]
Just want to say how much better this is now. :)
