### ISSUE TITLE
NaNs in meshes: `min` broken in some evaluators?

### ISSUE THREAD

**Issue by waywardmonkeys** [mkeeter/fidget#194]
We're still narrowing this down, but it seems like using a Tree like this one generates data with a lot of NaNs in it:

```
pub fn box_exact(extent_x: impl Into<Tree>, extent_y: impl Into<Tree>, extent_z: impl Into<Tree>) -> Tree {
    let (x, y, z) = Tree::axes();
    let dx = x.abs() - extent_x;
    let dy = y.abs() - extent_y;
    let dz = z.abs() - extent_z;
    length(dx.max(0.), dy.max(0.), dz.max(0.)) + dy.max(dz).max(dx).min(0.)
}
```

Through some trial and error, we've seen the NaNs when we still had a `min` in play.

This is with current `main` (1aad8a144fb5232a311fe69eae6f29ae834ca8f9) and using a `VmShape` to create a mesh.

**Comment by waywardmonkeys** [comment]
There is an `Octree` test that uses a different formulation:

```
    fn cube(bx: [f32; 2], by: [f32; 2], bz: [f32; 2]) -> Tree {
        let (x, y, z) = Tree::axes();
        let x_bounds = (bx[0] - x.clone()).max(x - bx[1]);
        let y_bounds = (by[0] - y.clone()).max(y - by[1]);
        let z_bounds = (bz[0] - z.clone()).max(z - bz[1]);
        x_bounds.max(y_bounds).max(z_bounds)
    }
```

**Comment by waywardmonkeys** [comment]
Changing that test to use my function and do a box with extents `[2., 0.3, 0.6]` results in 0 vertices, which also feels wrong.

**Comment by waywardmonkeys** [comment]
A quick hack to `max(..., 0.000001)` did result in the box getting meshed.

Thanks!

Hmm, wonder if that's related to my torus blowing up too then.

**Comment by mkeeter** [comment]
I do wonder whether we should be providing better errors, e.g. returning an explicit error of `InvalidGradientAt(x, y, z)`.  Any thoughts?

**Comment by waywardmonkeys** [comment]
Yes, please!
