### ISSUE TITLE
Vertices placed far outside their cell bounds

### ISSUE THREAD

**Issue by julianschuler** [mkeeter/fidget#53]
Hi,

for certain mesh settings and models vertices are placed far outside their respective cell bounds:

![escaping-vertices](https://github.com/mkeeter/fidget/assets/31921487/12159d89-2929-4a05-839e-74ac71ed65d4)

### Minimum working example

```rust
use fidget::{
    context::{IntoNode, Node},
    eval::MathShape,
    jit::JitShape,
    mesh::{Octree, Settings},
    Context, Error,
};

pub struct Sphere {
    radius: f64,
}

impl Sphere {
    pub fn new(radius: f64) -> Self {
        Self { radius }
    }
}

impl IntoNode for Sphere {
    fn into_node(self, context: &mut Context) -> Result<Node, Error> {
        let x = context.x();
        let y = context.y();
        let z = context.z();

        let x_squared = context.square(x)?;
        let y_squared = context.square(y)?;
        let z_squared = context.square(z)?;

        let sum = context.add(x_squared, y_squared)?;
        let sum = context.add(sum, z_squared)?;
        let length = context.sqrt(sum)?;

        context.sub(length, self.radius)
    }
}

fn main() -> Result<(), Error> {
    let settings = Settings {
        threads: 12,
        min_depth: 4,
        max_depth: 4,
    };

    let mut context = Context::new();
    let sphere = Sphere::new(0.75);
    let root = sphere.into_node(&mut context)?;

    let shape = JitShape::new(&context, root)?;
    let mesh = Octree::build(&shape, settings).walk_dual(settings);

    let invalid_vertices = mesh
        .vertices
        .iter()
        .filter(|vertex| vertex.norm() > 10.0)
        .count();
    dbg!(invalid_vertices);

    Ok(())
}
```

The output is the following (expected 0 invalid vertices):

```
[src/main.rs:56:5] invalid_vertices = 2
```

### Possible workaround

I traced this down to the QEF solving and noticed the following: When truncating the singular values below `0.1` as described in "Dual Contouring: The Secret Sauce", this issue does not occur anymore. Compared to the current approach this can result in way larger errors but seems to place the vertices more accurately in those cases.

However, this does not work well with models like a cone which is confirmed by the `test_cone_vert` unit test.

### Additional observations

While for the sphere in the MWE the issue only happens rarely for specific combinations of mesh settings and radius, for a (mitered) box with a taper it occurs for nearly all combinations of taper scale, box size and mesh settings.

This may indicate that the issue may be related to vertices within flat sections, though I have not investigated this further.

**Comment by mkeeter** [comment]
Thanks for the report, and welcome to the horrors of meshing with QEFs 🙃 

You're correct that it was bad handling of vertices within locally-flat sections of the mesh!

The QEF solver heuristic picked a full-rank solution (which was way off in space), because the `N - 1`-rank solution was worse; in fact, it should have chosen the `N - 2`-rank solution.  I brought in another heuristic from `libfive` to fix it, and added a unit test.

**Comment by julianschuler** [comment]
Thank you for the quick fix and explanation! You are awesome!
