### ISSUE TITLE
JIT support for windows.

### ISSUE THREAD

**Issue by LukeP0WERS** [mkeeter/fidget#74]
Hi, I'm super impressed with your work in implicit modeling and excited to start integrating this with my game engine. I use windows for development and so I am interested and getting the JIT compiler working for windows. You mentioned that you had something that might work and just haven't been able to test it, and I would be more than willing to try and get that working. I've taken a look at the code, and it seems like the only thing missing is an `Mmap` impl for windows. Do you have any code for that lying around that?

**Comment by mkeeter** [comment]
I'm putting stuff together over in #75, take a look!

**Comment by mkeeter** [comment]
All of the JIT tests passed on the first try 🥳 , but oddly enough, it's getting stuck in multithreaded meshing.

This is _probably_ due to a deadlock somewhere in my [terrible homebrew thread pool](https://github.com/mkeeter/fidget/blob/main/fidget/src/mesh/mt/pool.rs)!

**Comment by LukeP0WERS** [comment]
Ok sick, I'm going to try and get familiar with the crate and i'll let you know if anything goes wrong. Thankfully my game engine renders sdfs with voxels so that shouldn't be too pressing of an issue.
