### ISSUE TITLE
Offer library to link?

### ISSUE THREAD

**Issue by lf94** [mkeeter/fidget#9]
Just noting a feature request to offer a library like libfive - I can try my hand at it probably in a month or two.

**Comment by mkeeter** [comment]
There's already a library: it's the [fidget crate](https://crates.io/crates/fidget) 😉 

To keep the project scope manageable, I'm not planning to add a C API.  If you'd like to write one, I'd suggest putting it into a separate crate, and I'd be happy to link it in the README.
